### ISSUE TITLE
kSFS

### ISSUE THREAD

**Issue by barlavi1** [harrispopgen/mutyper#15]
Hi,
I am trying to construct the kSFS table in order to use it as an input for MUSHI.
I'm using 10 homozygous samples and the resulting sfs matrix has 19 rows, when rows 1,3,5,7,9,..,19 are all zeros. 
Is that a logical output? 

Thanks,
Bar

**Comment by WSDeWitt** [comment]
Hi Bar,

The rows correspond to allele frequencies, so if all the variants in your VCF are homozygous, they will have even-numbered allele frequencies in the sample, and the odd rows will contain zeros. I'll follow up via email to ask more about your use case.

 - Will
