### ISSUE TITLE
Fix references in  https://github.com/harrispopgen/mutyper/blob/master/paper/paper.md

### ISSUE THREAD

**Issue by izabelcavassim** [harrispopgen/mutyper#42]
In the session [Applications](https://github.com/harrispopgen/mutyper/blob/master/paper/paper.md#applications) of their article, the authors give examples of where users have utilized mutyper but the authors have not shared the specific citations for these articles. I would like to see references for the work they have mentioned, specifically: @sasani2022 and @Vollger2022.

**Comment by WSDeWitt** [comment]
My understanding was that the markdown source file should have an empty References section, but then the JOSS editorialbot compiles the paper pdf using the bibtext file to fill in the references cited (with tags like `@sasani2022`). It looks like the references are rendering in the pdf compiled from the markdown + bibtext file, linked by the editorialbot comment here: https://github.com/openjournals/joss-reviews/issues/5227#issuecomment-1458443035.

Does this look ok?

**Comment by izabelcavassim** [comment]
sorry that works, are you intending to leave the markdown in the repo too? Is there a way to print it out to markdown or only when rendered to pdf? I guess if you create references manually on markdown it would be overwritten by the pdf? I never tried so I don't know.

**Comment by WSDeWitt** [comment]
We haven't found a way to also render the references in the formatted markdown, but in PR #47 we've added a [README](https://github.com/harrispopgen/mutyper/tree/joss-review/paper)  in the `paper/` subdirectory to explain that the markdown paper and bibtex references are source files for a pdf paper build. We also provide a link to the JOSS review page (where the pdf paper would appear).
