### ISSUE TITLE
Add Community Guidelines

### ISSUE THREAD

**Issue by izabelcavassim** [harrispopgen/mutyper#44]
I couldn't find anything related to community guidelines.
Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Can you add that?

**Comment by WSDeWitt** [comment]
In PR #47 we've added a [CONTRIBUTING](https://github.com/harrispopgen/mutyper/blob/joss-review/docs/CONTRIBUTING.md) page to the docs. After merging the PR, this page will also be rendered in the sphinx documentation alongside the developer documentation page.

**Comment by WSDeWitt** [comment]
Here is the new docs page: https://harrispopgen.github.io/mutyper/CONTRIBUTING.html
